"""initial schema

Revision ID: 09ba2fd85bb4
Revises: 
Create Date: 2026-04-03 06:47:07.053732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09ba2fd85bb4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('api_football_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('club', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_football_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clerk_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('leagues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('invite_code', sa.String(), nullable=False),
    sa.Column('commissioner_id', sa.Uuid(), nullable=False),
    sa.Column('max_teams', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('draft_scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commissioner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_table('gameweeks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('locks_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('draft_position', sa.Integer(), nullable=True),
    sa.Column('standings_points', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'name', name='uq_team_name_per_league'),
    sa.UniqueConstraint('league_id', 'user_id', name='uq_one_team_per_user_per_league')
    )
    op.create_table('activity_feed',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('actor_team_id', sa.Uuid(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draft_picks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('pick_number', sa.Integer(), nullable=False),
    sa.Column('picked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('free_agent_claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('player_in_id', sa.Uuid(), nullable=False),
    sa.Column('player_out_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['player_in_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_out_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gameweek_selections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('gameweek_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('is_captain', sa.Boolean(), nullable=False),
    sa.Column('is_vice_captain', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'gameweek_id', 'player_id', name='uq_selection')
    )
    op.create_table('matchups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('gameweek_id', sa.Uuid(), nullable=False),
    sa.Column('home_team_id', sa.Uuid(), nullable=False),
    sa.Column('away_team_id', sa.Uuid(), nullable=False),
    sa.Column('home_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('away_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gameweek_id', 'away_team_id', name='uq_away_matchup'),
    sa.UniqueConstraint('gameweek_id', 'home_team_id', name='uq_home_matchup')
    )
    op.create_table('player_match_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('gameweek_id', sa.Uuid(), nullable=False),
    sa.Column('base_points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('bonus_points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total_points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sub_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'gameweek_id', name='uq_player_gameweek_score')
    )
    op.create_table('squad_players',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('acquired_via', sa.String(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'player_id', name='uq_player_per_team')
    )
    op.create_table('trades',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('proposer_team_id', sa.Uuid(), nullable=False),
    sa.Column('receiver_team_id', sa.Uuid(), nullable=False),
    sa.Column('proposer_player_id', sa.Uuid(), nullable=False),
    sa.Column('receiver_player_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('parent_trade_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['parent_trade_id'], ['trades.id'], ),
    sa.ForeignKeyConstraint(['proposer_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['proposer_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['receiver_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['receiver_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('squad_players')
    op.drop_table('player_match_scores')
    op.drop_table('matchups')
    op.drop_table('gameweek_selections')
    op.drop_table('free_agent_claims')
    op.drop_table('draft_picks')
    op.drop_table('activity_feed')
    op.drop_table('teams')
    op.drop_table('gameweeks')
    op.drop_table('leagues')
    op.drop_table('users')
    op.drop_table('players')
    # ### end Alembic commands ###
